### ISSUE TITLE
Can't slide in mobile. Only tap works.

### ISSUE THREAD

**Issue by supreeth-k** [pupunzi/jquery.mb.valueSlider#3]
For mobile devices, sliding isn't working. Only tapping on the screen at a particular point is a way of selecting the values. Are any fixes available for this?

**Comment by pupunzi** [comment]
Just updated to the 1.7.0 release. It works on mobile now.
https://github.com/pupunzi/jquery.mb.slider/releases

**Comment by supreethkrishnamurthy** [comment]
> Just updated to the 1.7.0 release. It works on mobile now.
> https://github.com/pupunzi/jquery.mb.slider/releases

Thanks!

**Comment by supreethkrishnamurthy** [comment]
Is there any additional configs we need to use for it to work on mobile? I tried with release 1.7.0 and sliding didn't work.

**Comment by supreeth-k** [comment]
Thanks! It is working now.
